"""Criação da tabela assunto.

Revision ID: bbf05ca57c5f
Revises: 9e253352aa63
Create Date: 2025-03-26 17:58:02.883548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf05ca57c5f'
down_revision: Union[str, None] = '9e253352aa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('id_assunto_pai', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['id_assunto_pai'], ['assunto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'disciplina_id', 'usuario_id', name='uq_assunto_disciplina_usuario')
    )
    op.create_table('concurso_disciplina_assunto',
    sa.Column('concurso_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('assunto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assunto_id'], ['assunto.id'], ),
    sa.ForeignKeyConstraint(['concurso_id'], ['concurso.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.PrimaryKeyConstraint('concurso_id', 'disciplina_id', 'assunto_id'),
    sa.UniqueConstraint('concurso_id', 'disciplina_id', 'assunto_id', name='uq_concurso_disciplina_assunto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concurso_disciplina_assunto')
    op.drop_table('assunto')
    # ### end Alembic commands ###
